apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ab19ma2l6-java-quarkus
  janus-idp.io/tekton: ab19ma2l6-java-quarkus
  backstage.io/kubernetes-id: ab19ma2l6-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ab19ma2l6-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
