apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ab19ma2l6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ab19ma2l6-java-quarkus-gitops